# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Deep Learning Portfolio
author: Keith Laspoña
logo: logo.png

# Do NOT execute notebooks during build (just use saved outputs)
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Optional references file
bibtex_bibfiles:
  - references.bib

# Repository settings
repository:
  url: https://github.com/keithlaspona/deeplearning  # Your repo URL
  path_to_book: .  # Book is at repo root
  branch: main

# GitHub buttons
html:
  use_issues_button: true
  use_repository_button: true
